package org.firstinspires.ftc.teamcode;

import java.util.Objects;

public class DrivePower {
    public final double rightFor, rightBack, leftFor, leftBack;

    public DrivePower(double rightFor, double rightBack, double leftFor, double leftBack) {
        this.rightFor = rightFor;
        this.rightBack = rightBack;
        this.leftFor = leftFor;
        this.leftBack = leftBack;
    }

    /**
     * Generated by Android Studio.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DrivePower that = (DrivePower) o;
        return Double.compare(that.rightFor, rightFor) == 0 &&
                Double.compare(that.rightBack, rightBack) == 0 &&
                Double.compare(that.leftFor, leftFor) == 0 &&
                Double.compare(that.leftBack, leftBack) == 0;
    }

    /**
     * Generated by Android Studio.
     */
    @Override
    public int hashCode() {
        return Objects.hash(rightFor, rightBack, leftFor, leftBack);
    }

    /**
     * Generated by Android Studio.
     */
    @Override
    public String toString() {
        return "DrivePower{" +
                "rightFor=" + rightFor +
                ", rightBack=" + rightBack +
                ", leftFor=" + leftFor +
                ", leftBack=" + leftBack +
                '}';
    }

}
